name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # required for gitversion to work

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test (.NET Framework)
      run: dotnet test --no-build --verbosity normal -f net462

    - name: Test (.NET Core)
      run: dotnet test --no-build --verbosity normal -f netcoreapp3.1

  pack:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Package
      run: dotnet pack -c Release --verbosity normal

    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: NaturalMouseMotionSharp/bin/Release/NaturalMouseMotionSharp.*.nupkg

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: pack
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: nupkg

    - name: Push to NuGet
      run: dotnet nuget push *.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}
