name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # required for gitversion to work

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test (.NET Framework)
      run: dotnet test --no-build --verbosity normal -f net462

    - name: Test (.NET Core)
      run: dotnet test --no-build --verbosity normal -f netcoreapp3.1

    - name: Package
      run: dotnet pack -c Release --no-restore --verbosity normal

    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: NaturalMouseMotionSharp/bin/Release/NaturalMouseMotionSharp.*.nupkg
